name: Attach zip to release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build zip
        env:
          ZIP_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
        run: zip -r "$ZIP_NAME" . -x@.distignore

      - name: Attach to release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip